const mongoose = require('mongoose');


const applicationSchema = new mongoose.Schema ({
    agent: String,
    id : String,
    slcFunded : String,
    residencyStatus : String,
    euSC : String,
    programmeGroup : String,
    course : String,
    intake : String,
    deliveryPattern : String,
    courseLevel : String,
    entryLevel : String,
    courseFee : String,
    firstYearFee : String,
    title : String,
    forename1 : String,
    forename2 : String,
    forename3 : String,
    prefFirstName : String,
    surname : String,
    prevSurname : String,
    gender : String,
    email : String,
    advanceEntry : String,
    phone : String,
    nationality : String,
    dualNationality : String,
    cOBirth : String,
    ethicOrigin : String,
    dOBirth : String,
    highestQualPreUK : String,
    highestQual : String,
    lastInstitution : String,
    institution : String,
    hesaNo : String,
    uLN : String,
    qualification : String,
    yearAchieved : String,
    subject : String,
    grade : String,
    passportNo : String,
    passportExp : String,
    passportIssuePlace : String,
    careLeaver : String,
    disability : String,
    liveInUk : String,
    permHouseNumber : String,
    permStreet : String,
    permCityTown : String,
    permCountyState : String,
    permPostCode : String,
    permCountry : String,
    curHouseNumber : String,
    curStreet : String,
    curCityTown : String,
    curCountyState : String,
    curPostCode : String,
    curCountry : String,
    nokName : String,
    nokRelation : String,
    nokPhone : String,
    nokEmail : String,
    personalStatement : String,
    attachedFiles : String,
    submittedOn : String,
    status : String,
    offer : String,
    registrationEmail : String,
    enrolmentStatus : String,
    applicant: String
})


module.exports = mongoose.model("Application", applicationSchema);
